### ISSUE TITLE
[Feature Request]: get all URI fields separated

### ISSUE THREAD

**Issue by wonko** [exoscale/terraform-provider-exoscale#365] opened 2024-06-03 08:32 UTC
### What feature would you like to have in the provider?

When using

```
data "exoscale_database_uri" "example" {
  name = exoscale_database.example.name
  type = exoscale_database.example.type
  zone = exoscale_database.example.zone
}
```

the only returned field is "uri". It would be good to have all fields which make up the uri as separate fields, so I can construct a URI myself with a different username, db, etc.

The main fields I need would be:
- hostname
- port
- scheme (`postgres` in the case of 'type = pg')
- any additional required parameters

It would be handy if this data is exposed on the creating resource as well (the `exoscale_database` resource), the constant creating and reading back of data is cumbersome.

**Comment by kobajagi** [comment] 2024-07-10 10:14
Hi @wonko . This is a duplicate of #279 . I'll close this one and you can follow progress in the other ticket.

> It would be handy if this data is exposed on the creating resource as well (the exoscale_database resource), the constant creating and reading back of data is cumbersome.

We want to keep secrets (database password) out of the terraform state where possible, this is why `exoscale_database_uri` exists.

**Closed as completed by kobajagi** 2024-07-10 10:14 UTC
Labels: feature request
