### ISSUE TITLE
All nodes removed when removing one node pool

### ISSUE THREAD

**Issue by raphink** [exoscale/terraform-provider-exoscale#122] opened 2021-09-01 15:31 UTC
I created a cluster with two node pools. Then I removed one node pool, but all the nodes were removed from the cluster.

Tainting the node pool and applying again restored new nodes to the cluster.

**Comment by falzm** [comment] 2021-09-01 15:32
@raphink can you please share your Terraform configuration so we can reproduce on our side?

**Comment by raphink** [comment] 2021-09-01 16:23
I can try to prepare a MWE. I'm using our devops-stack, so it looks something like:

```hcl
module "cluster" {
  source = "git::https://github.com/camptocamp/devops-stack.git//modules/sks/exoscale?ref=v0.45.0"

  cluster_name = "elastic-test"
  zone         = "de-fra-1"

  kubernetes_version = "1.21.4"

  nodepools = {
    "router-elastic-test" = {
      size          = 2
      instance_type = "standard.large"
    }

    "compute-elastic-test" = {
      size          = 2
      instance_type = "standard.large"
    }
  }
```

The `nodepools` get passed down to the camptocamp/sks/exoscale module (https://registry.terraform.io/modules/camptocamp/sks/exoscale) where it generates one `exoscale_sks_nodepool` resource per node pool: https://github.com/camptocamp/terraform-exoscale-sks/blob/main/main.tf#L45

As a result, when removing one nodepool from the list, it removes the corresponding `exoscale_sks_nodepool` resource, leaving the other untouched (verified in the terraform plan). However, all nodes were removed from the cluster when applying.

It should be rather simple to reproduce by using two `exoscale_sks_nodepool` resources, then removing one and applying.

**Comment by falzm** [comment] 2021-09-02 07:13
@raphink with the following procedure I can't reproduce your problem:

Test configuration:

```hcl
terraform {
  required_providers {
    exoscale = {
      source  = "exoscale/exoscale"
      version = "0.28.0"
    }
  }
}

locals {
  zone = "de-fra-1"
}

resource "exoscale_sks_cluster" "test" {
  zone = local.zone
  name = "test"
}

resource "exoscale_sks_nodepool" "np1" {
  zone          = local.zone
  cluster_id    = exoscale_sks_cluster.test.id
  name          = "np1"
  instance_type = "standard.small"
  size          = 2
}

resource "exoscale_sks_nodepool" "np2" {
  zone          = local.zone
  cluster_id    = exoscale_sks_cluster.test.id
  name          = "np2"
  instance_type = "standard.small"
  size          = 2
}
```

Applying:

```console
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  + create

Terraform will perform the following actions:

  # exoscale_sks_cluster.test will be created
  + resource "exoscale_sks_cluster" "test" {
      + addons         = (known after apply)
      + cni            = "calico"
      + created_at     = (known after apply)
      + endpoint       = (known after apply)
      + exoscale_ccm   = true
      + id             = (known after apply)
      + metrics_server = true
      + name           = "test"
      + nodepools      = (known after apply)
      + service_level  = "pro"
      + state          = (known after apply)
      + version        = (known after apply)
      + zone           = "de-fra-1"
    }

  # exoscale_sks_nodepool.np1 will be created
  + resource "exoscale_sks_nodepool" "np1" {
      + cluster_id       = (known after apply)
      + created_at       = (known after apply)
      + disk_size        = 50
      + id               = (known after apply)
      + instance_pool_id = (known after apply)
      + instance_prefix  = "pool"
      + instance_type    = "standard.small"
      + name             = "np1"
      + size             = 2
      + state            = (known after apply)
      + template_id      = (known after apply)
      + version          = (known after apply)
      + zone             = "de-fra-1"
    }

  # exoscale_sks_nodepool.np2 will be created
  + resource "exoscale_sks_nodepool" "np2" {
      + cluster_id       = (known after apply)
      + created_at       = (known after apply)
      + disk_size        = 50
      + id               = (known after apply)
      + instance_pool_id = (known after apply)
      + instance_prefix  = "pool"
      + instance_type    = "standard.small"
      + name             = "np2"
      + size             = 2
      + state            = (known after apply)
      + template_id      = (known after apply)
      + version          = (known after apply)
      + zone             = "de-fra-1"
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

exoscale_sks_cluster.test: Creating...
exoscale_sks_cluster.test: Still creating... [10s elapsed]
exoscale_sks_cluster.test: Still creating... [20s elapsed]
exoscale_sks_cluster.test: Still creating... [30s elapsed]
exoscale_sks_cluster.test: Still creating... [40s elapsed]
exoscale_sks_cluster.test: Still creating... [50s elapsed]
exoscale_sks_cluster.test: Still creating... [1m0s elapsed]
exoscale_sks_cluster.test: Still creating... [1m10s elapsed]
exoscale_sks_cluster.test: Still creating... [1m20s elapsed]
exoscale_sks_cluster.test: Still creating... [1m30s elapsed]
exoscale_sks_cluster.test: Creation complete after 1m34s [id=e78ad9b6-f869-4492-aa1e-fd859337e26d]
exoscale_sks_nodepool.np1: Creating...
exoscale_sks_nodepool.np2: Creating...
exoscale_sks_nodepool.np1: Creation complete after 4s [id=9eccd769-a282-4fe2-9e58-5ef3bc716743]
exoscale_sks_nodepool.np2: Creation complete after 4s [id=45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
```

Removing Nodepool `np2` from the TF configuration, then applying:

```console
$ terraform apply
exoscale_sks_nodepool.np2: Refreshing state... [id=45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4]
exoscale_sks_cluster.test: Refreshing state... [id=e78ad9b6-f869-4492-aa1e-fd859337e26d]
exoscale_sks_nodepool.np1: Refreshing state... [id=9eccd769-a282-4fe2-9e58-5ef3bc716743]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # exoscale_sks_cluster.test has been changed
  ~ resource "exoscale_sks_cluster" "test" {
        id             = "e78ad9b6-f869-4492-aa1e-fd859337e26d"
        name           = "test"
      ~ nodepools      = [
          + "45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4",
          + "9eccd769-a282-4fe2-9e58-5ef3bc716743",
        ]
        # (11 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using
ignore_changes, the following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  - destroy

Terraform will perform the following actions:

  # exoscale_sks_nodepool.np2 will be destroyed
  - resource "exoscale_sks_nodepool" "np2" {
      - cluster_id       = "e78ad9b6-f869-4492-aa1e-fd859337e26d" -> null
      - created_at       = "2021-09-02 07:04:27 +0000 UTC" -> null
      - disk_size        = 50 -> null
      - id               = "45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4" -> null
      - instance_pool_id = "a251e012-5bc0-4c99-beac-c48cf177f537" -> null
      - instance_prefix  = "pool" -> null
      - instance_type    = "standard.small" -> null
      - name             = "np2" -> null
      - size             = 2 -> null
      - state            = "running" -> null
      - template_id      = "50fa7de4-bca6-4e9f-b17b-1ec0d389f409" -> null
      - version          = "1.22.1" -> null
      - zone             = "de-fra-1" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

exoscale_sks_nodepool.np2: Destroying... [id=45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4]
exoscale_sks_nodepool.np2: Destruction complete after 3s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

Confirming that the Nodepool `np1` still exists:

```console
$ terraform plan
exoscale_sks_cluster.test: Refreshing state... [id=e78ad9b6-f869-4492-aa1e-fd859337e26d]
exoscale_sks_nodepool.np1: Refreshing state... [id=9eccd769-a282-4fe2-9e58-5ef3bc716743]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # exoscale_sks_cluster.test has been changed
  ~ resource "exoscale_sks_cluster" "test" {
        id             = "e78ad9b6-f869-4492-aa1e-fd859337e26d"
        name           = "test"
      ~ nodepools      = [
          - "45c7b034-c64e-4ecf-b4cb-71e0d6e67ec4",
            # (1 unchanged element hidden)
        ]
        # (11 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may
include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.
```

Compute instances belonging to the Nodepool also still exist:

```console
$ exo sks np show -z de-fra-1 test np1
┼──────────────────────┼──────────────────────────────────────┼
│     SKS NODEPOOL     │                                      │
┼──────────────────────┼──────────────────────────────────────┼
│ ID                   │ 9eccd769-a282-4fe2-9e58-5ef3bc716743 │
│ Name                 │ np1                                  │
│ Description          │                                      │
│ Creation Date        │ 2021-09-02 07:04:27 +0000 UTC        │
│ Instance Pool ID     │ b7a18e9b-fb45-47a1-9b62-3e94bc00607c │
│ Instance Prefix      │ pool                                 │
│ Instance Type        │ small                                │
│ Template             │ SKS Node (kubelet 1.22.1)            │
│ Disk Size            │ 50                                   │
│ Anti Affinity Groups │ n/a                                  │
│ Security Groups      │ n/a                                  │
│ Private Networks     │ n/a                                  │
│ Version              │ 1.22.1                               │
│ Size                 │ 2                                    │
│ State                │ running                              │
│ Labels               │ n/a                                  │
┼──────────────────────┼──────────────────────────────────────┼

$ exo compute instance list
┼──────────────────────────────────────┼──────────────────┼──────────┼────────────────┼─────────────────┼─────────┼
│                  ID                  │       NAME       │   ZONE   │      TYPE      │   IP ADDRESS    │  STATE  │
┼──────────────────────────────────────┼──────────────────┼──────────┼────────────────┼─────────────────┼─────────┼
│ fcfa9141-4cb8-4fee-8e1b-56f91a9c3a97 │ pool-b7a18-gnsko │ de-fra-1 │ standard.small │ 194.182.169.55  │ running │
│ 36031bf2-cb27-49d5-a70b-63033113c2b1 │ pool-b7a18-yjxug │ de-fra-1 │ standard.small │ 194.182.168.226 │ running │
┼──────────────────────────────────────┼──────────────────┼──────────┼────────────────┼─────────────────┼─────────┼
```

**Comment by raphink** [comment] 2021-09-02 14:29
The instance pool & the instances still existed in my case, too. They were just not in the Kubernetes cluster anymore.

**Comment by falzm** [comment] 2021-09-02 14:33
Hum, sounds like an issue indeed – although I'm not sure how the Terraform provider relates to that. Can you reproduce this behavior using the `exo sks nodepool delete` CLI command? Basically does the same thing as the TF provider.

**Comment by falzm** [comment] 2021-09-02 14:42
@raphink we managed to reproduce your issue internally, however it is indeed a bug in our SKS offering – unrelated to our Terraform provider. I'm gonna go ahead and close this issue, can you please open a ticket at the Exoscale support, so you can track the resolution of the issue as our team works on a fix?

**Closed as completed by falzm** 2021-09-02 14:42 UTC
