### ISSUE TITLE
datasource_exoscale_compute_instance should be able to list all instances

### ISSUE THREAD

**Issue by Jil** [exoscale/terraform-provider-exoscale#142] opened 2022-01-04 11:58 UTC
The `datasource_exoscale_compute_instance` should be able to return all instances of the given zone, leveraging https://openapi-v2.exoscale.com/#operation-get-instance 

**Current behavior:**
The datasource expects a name or ID.

**Expected behavior:**
When no filter is given, all instances are returned.

**Comment by jessicatoscani** [comment] 2022-01-10 15:18
Hi @Jil, the datasource `exoscale_compute_instance` was designed to return only one instance.
Indeed it would be helpful to get all the instances. We'll add it to our To-Do list, this should be ready soon.

**Comment by PhilippeChepy** [comment] 2022-06-23 06:04
This is addressed by https://github.com/exoscale/terraform-provider-exoscale/pull/178, which is available since v0.37.0

**Closed as completed by PhilippeChepy** 2022-06-23 06:04 UTC
Labels: feature request
